
create table document_kf(
DOCUMENT_NO	NUMBER(14) not null,
BAR_CODE_NO	VARCHAR2(30),
BUSINESS_TYPE	VARCHAR2(2),
DOCUMENT_TYPE	VARCHAR2(4),
DOCUMENT_CODE	VARCHAR2(6),
SCAN_TIME	DATE,
SCAN_SITE	VARCHAR2(10),
SCAN_OPERATOR	VARCHAR2(50),
PAGE_COUNT	NUMBER(4),
REGION_CODE	VARCHAR2(10),
STATUS	VARCHAR2(1),
CREATION_DATE	DATE,
LCD	DATE,
LCU	VARCHAR2(50),
DOCUMENT_ID	NUMBER(14),
FILE_TYPE	VARCHAR2(3),
DOCUMENT_SIZE	NUMBER(10),
PRIORITY	NUMBER(2),
SCAN_SEQNO	VARCHAR2(50),
IS_MIGRATED VARCHAR2(1) DEFAULT 'N'
);

create table document_kb(
DOCUMENT_NO	NUMBER(14) not null,
BAR_CODE_NO	VARCHAR2(30),
BUSINESS_TYPE	VARCHAR2(2),
DOCUMENT_TYPE	VARCHAR2(4),
DOCUMENT_CODE	VARCHAR2(6),
SCAN_TIME	DATE,
SCAN_SITE	VARCHAR2(10),
SCAN_OPERATOR	VARCHAR2(50),
PAGE_COUNT	NUMBER(4),
REGION_CODE	VARCHAR2(10),
STATUS	VARCHAR2(1),
CREATION_DATE	DATE,
LCD	DATE,
LCU	VARCHAR2(50),
DOCUMENT_ID	NUMBER(14),
FILE_TYPE	VARCHAR2(3),
DOCUMENT_SIZE	NUMBER(10),
PRIORITY	NUMBER(2),
SCAN_SEQNO	VARCHAR2(50),
IS_MIGRATED VARCHAR2(1) DEFAULT 'N'
);

create table document_url(
SEQ	NUMBER(14) not null,
URL	 VARCHAR2(50)
);

document_url